### ISSUE TITLE
Error: child index out of range

### ISSUE THREAD

**Issue by satyendra22** [LimberDuck/nessus-file-analyzer#5]
While parsing its throwing below error
[2021-01-13 16:45:01.099777] [action=info] [source_file_name=ERROR Parsing [1/1] nessus files] 
[2021-01-13 16:45:01.111838] [action=info] [source_file_name=child index out of range] 

  File "C:\Users\student\AppData\Roaming\Python\Python37\site-packages\nessus_file_reader\scan\scan.py", line 59, in server_preference_value
    for preference in root[0][1][0].findall("preference"):
IndexError: child index out of range

**Comment by kkenderesi** [comment]
Same issue. I am trying to analyse a Tenable.io generated nessus file.

**Comment by damian-krawczyk** [comment]
**Sorry for late response!** 
@satyendra22 what is the source of your `*.nessus` file? Does it Tenable.io as in @kkenderesi example?

**Comment by hackstrip** [comment]
The problem is probably the parsing of the preferences part of the nessus file, (see line 59 of scan.py)
I had some success in changing 'root[0][1][0].findall("preference")' to 'root[0][2][0].findall("preference")'

**Comment by damian-krawczyk** [comment]
Hi @hackstrip, @mplattner, @satyendra22, @kkenderesi,
Can you check it now? Make sure that you have below in pointed version:

- `nessus-file-analyzer 0.7.2`
- `nessus-file-reader   0.4.1`

**Comment by mplattner** [comment]
Yes, there are no errors with the .nessus files that did throw the error with the previous analyzer version 👍
Sorry for my late response.
